import { GoogleGenAI, Type } from "@google/genai";
import axios from "axios";
import * as fs from "fs/promises";
import * as path from "path";
import { StoryboardScene } from "../../types.js";

// Initialize Gemini client with proper telemetry headers
const gemini = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY || "",
  httpOptions: {
    headers: {
      "User-Agent": "aistudio-build",
    },
  },
});

export class AIService {
  private static async retry<T>(
    fn: () => Promise<T>,
    logFn: (msg: string) => void,
    retries = 3,
    delay = 2000
  ): Promise<T> {
    try {
      return await fn();
    } catch (err: any) {
      if (retries > 0) {
        logFn(`Gemini API call failed (${err.message || err}). Retrying in ${delay}ms... (${retries} attempts left)`);
        await new Promise((resolve) => setTimeout(resolve, delay));
        return this.retry(fn, logFn, retries - 1, delay * 2);
      }
      throw err;
    }
  }

  private static getClaudeHeaders() {
    const apiKey = process.env.CLAUDE_API_KEY || process.env.ANTHROPIC_API_KEY || "";
    return {
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
      "content-type": "application/json",
    };
  }

  private static getElevenLabsHeaders() {
    return {
      "xi-api-key": process.env.ELEVENLABS_API_KEY || "",
      "content-type": "application/json",
    };
  }

  private static getHiggsfieldHeaders() {
    return {
      "Authorization": `Bearer ${process.env.HIGGSFIELD_API_KEY || ""}`,
      "content-type": "application/json",
    };
  }

  /**
   * Step 1: Generate Lyrics
   */
  public static async generateLyrics(
    topic: string,
    ageGroup: string,
    language: string,
    songStyle: string,
    logFn: (msg: string) => void
  ): Promise<string> {
    const prompt = `Write a cute, rhyming, educational children's song about: "${topic}".
Target Age Group: ${ageGroup}
Language: ${language}
Song Style: ${songStyle}
The song should be structured exactly as:
[Verse 1]
(4 simple lines)

[Chorus]
(4 simple catch lines, easy to repeat)

[Verse 2]
(4 simple lines)

[Chorus]
(Repeat chorus)

[Ending]
(2 simple lines of closure)`;

    const claudeKey = process.env.CLAUDE_API_KEY || process.env.ANTHROPIC_API_KEY;
    if (claudeKey) {
      logFn("Calling Claude API for lyrics generation...");
      try {
        const response = await axios.post(
          "https://api.anthropic.com/v1/messages",
          {
            model: "claude-3-5-sonnet-20241022",
            max_tokens: 1500,
            messages: [{ role: "user", content: prompt }],
          },
          { headers: this.getClaudeHeaders() }
        );
        const text = response.data.content[0].text;
        logFn("Lyrics successfully generated by Claude!");
        return text;
      } catch (err: any) {
        logFn(`Claude API failed (${err.message}). Falling back to Gemini...`);
      }
    }

    logFn("Calling Gemini API (gemini-3.5-flash) for lyrics generation...");
    const response = await this.retry(
      () =>
        gemini.models.generateContent({
          model: "gemini-3.5-flash",
          contents: prompt,
        }),
      logFn
    );
    const text = response.text || "";
    logFn("Lyrics successfully generated by Gemini!");
    return text;
  }

  /**
   * Step 2: Generate Storyboard
   */
  public static async generateStoryboard(
    lyrics: string,
    topic: string,
    videoStyle: string,
    logFn: (msg: string) => void
  ): Promise<StoryboardScene[]> {
    const prompt = `Based on the following children's lyrics, create a detailed, highly consistent 4-scene storyboard for a 1-minute video.
Lyrics:
${lyrics}

Topic: ${topic}
Video Visual Style: ${videoStyle} (e.g. Pixar-like, colorful, friendly, consistent characters)

Create exactly 4 scenes. Provide the response as a JSON array matching the StoryboardScene structure:
[
  {
    "id": 1,
    "timeStart": 0,
    "timeEnd": 15,
    "visual": "A detailed description of the physical action, characters, and settings for image generator. E.g. 'A cute yellow teddy bear brushing its white teeth with a small blue toothbrush in a bright, colorful cartoon bathroom.'",
    "cameraMovement": "E.g. 'Slow pan right'",
    "character": "Describe character details for consistency. E.g. 'Cute fluffy yellow teddy bear with big sparkly brown eyes'",
    "animation": "E.g. 'Teddy bear is smiling and moving the toothbrush back and forth'",
    "background": "E.g. 'Bright tiled bathroom with bubbles floating and a friendly sun looking in the window'",
    "mood": "E.g. 'Cheerful, playful'",
    "colorPalette": "E.g. 'Warm pastels, bright blues and yellows'",
    "subtitle": "Text overlay for lyrics during this scene",
    "narration": "Narration text corresponding to this scene"
  }
]
`;

    const schema = {
      type: Type.ARRAY,
      items: {
        type: Type.OBJECT,
        properties: {
          id: { type: Type.INTEGER },
          timeStart: { type: Type.NUMBER },
          timeEnd: { type: Type.NUMBER },
          visual: { type: Type.STRING },
          cameraMovement: { type: Type.STRING },
          character: { type: Type.STRING },
          animation: { type: Type.STRING },
          background: { type: Type.STRING },
          mood: { type: Type.STRING },
          colorPalette: { type: Type.STRING },
          subtitle: { type: Type.STRING },
          narration: { type: Type.STRING },
        },
        required: [
          "id",
          "timeStart",
          "timeEnd",
          "visual",
          "cameraMovement",
          "character",
          "animation",
          "background",
          "mood",
          "colorPalette",
          "subtitle",
          "narration",
        ],
      },
    };

    const claudeKey = process.env.CLAUDE_API_KEY || process.env.ANTHROPIC_API_KEY;
    if (claudeKey) {
      logFn("Calling Claude API for storyboard generation...");
      try {
        const response = await axios.post(
          "https://api.anthropic.com/v1/messages",
          {
            model: "claude-3-5-sonnet-20241022",
            max_tokens: 3000,
            messages: [{ role: "user", content: prompt + "\nOutput strictly raw JSON." }],
          },
          { headers: this.getClaudeHeaders() }
        );
        const text = response.data.content[0].text;
        const cleaned = text.substring(text.indexOf("["), text.lastIndexOf("]") + 1);
        const parsed = JSON.parse(cleaned);
        logFn("Storyboard successfully generated by Claude!");
        return parsed;
      } catch (err: any) {
        logFn(`Claude Storyboard generation failed (${err.message}). Falling back to Gemini...`);
      }
    }

    logFn("Calling Gemini API (gemini-3.5-flash) with responseSchema for storyboard...");
    const response = await this.retry(
      () =>
        gemini.models.generateContent({
          model: "gemini-3.5-flash",
          contents: prompt,
          config: {
            responseMimeType: "application/json",
            responseSchema: schema,
          },
        }),
      logFn
    );

    const parsed = JSON.parse(response.text || "[]");
    logFn(`Storyboard successfully generated by Gemini with ${parsed.length} scenes!`);
    return parsed;
  }

  /**
   * Step 3: Generate Background Music Track
   */
  public static async generateMusic(
    stylePrompt: string,
    duration: number,
    logFn: (msg: string) => void
  ): Promise<Buffer> {
    const elApiKey = process.env.ELEVENLABS_API_KEY;
    if (elApiKey) {
      logFn(`Calling ElevenLabs sound-effects/music API for backing track of style: "${stylePrompt}"...`);
      try {
        // Use ElevenLabs Sound Effects/Audio Generation endpoint for playful music loop
        const response = await axios.post(
          "https://api.elevenlabs.io/v1/sound-effects",
          {
            text: `Upbeat, playful children's song instrumental music track, happy marimba, playful acoustic guitar, ${stylePrompt}`,
            duration_seconds: Math.min(duration, 30), // Clamp to ElevenLabs max limits if any
            prompt_influence: 0.8,
          },
          {
            headers: this.getElevenLabsHeaders(),
            responseType: "arraybuffer",
          }
        );
        logFn("Background music successfully generated via ElevenLabs!");
        return Buffer.from(response.data);
      } catch (err: any) {
        logFn(`ElevenLabs Music API failed (${err.message}). Using local synthesis...`);
      }
    }

    logFn("ElevenLabs key missing/failed. Creating local playful synthesizer loop...");
    // Let's return an empty buffer or handle procedural fallback in the video service
    return Buffer.alloc(0);
  }

  /**
   * Step 4: Generate Vocals (Singing/Narration)
   */
  public static async generateVocals(
    lyricsText: string,
    voiceStyle: string,
    language: string,
    logFn: (msg: string) => void
  ): Promise<Buffer> {
    const cleanLyrics = lyricsText.replace(/\[.*?\]/g, "").trim(); // Remove section headers [Chorus] etc.
    const elApiKey = process.env.ELEVENLABS_API_KEY;

    if (elApiKey) {
      logFn(`Calling ElevenLabs TTS for vocal synthesis (${voiceStyle})...`);
      try {
        // Default voice IDs (pre-made cute or friendly voices)
        // Rachel: 21m00Tcm4TlvDq8ikWAM, Lily: pMsXgTz6vjD9cInZ3W4f
        const voiceId = "pMsXgTz6vjD9cInZ3W4f"; // Lily (cheerful, young)
        const response = await axios.post(
          `https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`,
          {
            text: cleanLyrics,
            model_id: "eleven_multilingual_v2",
            voice_settings: {
              stability: 0.5,
              similarity_boost: 0.75,
              style: 0.4,
              use_speaker_boost: true,
            },
          },
          {
            headers: this.getElevenLabsHeaders(),
            responseType: "arraybuffer",
          }
        );
        logFn("Vocals successfully generated via ElevenLabs!");
        return Buffer.from(response.data);
      } catch (err: any) {
        logFn(`ElevenLabs TTS failed (${err.message}). Falling back to Gemini TTS...`);
      }
    }

    logFn("Calling Gemini TTS API (gemini-3.1-flash-tts-preview) for children vocals...");
    try {
      const response = await this.retry(
        () =>
          gemini.models.generateContent({
            model: "gemini-3.1-flash-tts-preview",
            contents: [{ parts: [{ text: `Read this song lyrics cheerfully and rhythmically with pauses: ${cleanLyrics}` }] }],
            config: {
              responseModalities: ["AUDIO" as any],
              speechConfig: {
                voiceConfig: {
                  prebuiltVoiceConfig: { voiceName: "Puck" }, // Puck is energetic and cute
                },
              },
            },
          }),
        logFn
      );

      const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
      if (base64Audio) {
        logFn("Vocals successfully generated by Gemini TTS!");
        return Buffer.from(base64Audio, "base64");
      }
    } catch (err: any) {
      logFn(`Gemini TTS also failed: ${err.message}. Creating procedural narrator...`);
    }

    return Buffer.alloc(0);
  }

  /**
   * Step 6: Generate Scene Images
   */
  public static async generateSceneImage(
    prompt: string,
    index: number,
    logFn: (msg: string) => void
  ): Promise<Buffer> {
    const hfApiKey = process.env.HIGGSFIELD_API_KEY;
    if (hfApiKey) {
      logFn(`Calling Higgsfield Image Generation API for Scene ${index}...`);
      try {
        const response = await axios.post(
          "https://api.higgsfield.ai/v1/images/generations",
          {
            prompt: `Pixar style, extremely colorful, children friendly illustration: ${prompt}, 3d render, cute character design, consistent details, 16:9 aspect ratio, UHD, masterpiece`,
            aspect_ratio: "16:9",
            num_images: 1,
          },
          { headers: this.getHiggsfieldHeaders() }
        );
        const imageUrl = response.data.images[0].url;
        logFn(`Higgsfield Image generated: downloading...`);
        const imgDownload = await axios.get(imageUrl, { responseType: "arraybuffer" });
        return Buffer.from(imgDownload.data);
      } catch (err: any) {
        logFn(`Higgsfield Image API failed (${err.message}). Falling back to Gemini...`);
      }
    }

    logFn(`Calling Gemini API (gemini-3.1-flash-image) for Scene ${index} image...`);
    const response = await this.retry(
      () =>
        gemini.models.generateContent({
          model: "gemini-3.1-flash-image",
          contents: {
            parts: [
              {
                text: `Beautiful, ultra-high-quality, Pixar-style 3D animated children's book illustration. Extremely colorful, warm pastel tones, friendly characters, rich texture. Scene details: ${prompt}`,
              },
            ],
          },
          config: {
            imageConfig: {
              aspectRatio: "16:9",
              imageSize: "1K",
            },
          },
        }),
      logFn
    );

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData?.data) {
        logFn(`Gemini successfully generated image for Scene ${index}!`);
        return Buffer.from(part.inlineData.data, "base64");
      }
    }

    throw new Error(`Failed to generate image for Scene ${index}`);
  }

  /**
   * Step 7: Higgsfield Animation API
   */
  public static async generateSceneVideo(
    imagePath: string,
    prompt: string,
    index: number,
    logFn: (msg: string) => void
  ): Promise<Buffer | null> {
    const hfApiKey = process.env.HIGGSFIELD_API_KEY;
    if (hfApiKey) {
      logFn(`Calling Higgsfield Video Animation API for Scene ${index}...`);
      try {
        // Read the image and convert to base64 for Higgsfield image-to-video prompt
        const imgBuffer = await fs.readFile(imagePath);
        const imgBase64 = imgBuffer.toString("base64");

        const response = await axios.post(
          "https://api.higgsfield.ai/v1/videos/generations",
          {
            image: `data:image/png;base64,${imgBase64}`,
            prompt: `Soft gentle camera panning, character smiling and subtle movement, beautiful animated scene: ${prompt}`,
            duration: 5,
            aspect_ratio: "16:9",
          },
          { headers: this.getHiggsfieldHeaders() }
        );

        const videoUrl = response.data.video_url;
        logFn(`Higgsfield Video generated! Downloading animated scene...`);
        const videoDownload = await axios.get(videoUrl, { responseType: "arraybuffer" });
        return Buffer.from(videoDownload.data);
      } catch (err: any) {
        logFn(`Higgsfield Animation failed (${err.message}). Local Ken Burns transition will be used instead.`);
      }
    }

    logFn(`No Higgsfield video key or API failed. Using local Ken Burns pan/zoom animator for Scene ${index}.`);
    return null; // Signals to video renderer to use local image animation
  }
}
